exchange:
  name: delta
  env: testnet
  rest_url: https://api.india.delta.exchange
  ws_url: wss://socket.india.delta.exchange
  api_key: ${DELTA_API_KEY}
  api_secret: ${DELTA_API_SECRET}

instruments:
#  - symbol: RIVERUSD
#    quantity: 4
#    max_positions: 1
#    resolution: 3m
##    trailing_amount_pct: 0.01
#    ema_impulse_threshold: 0.0050
#    bootstrap_length: 300
#    leverage: 20
#    take_profit_pct: 0.005  # 0.25%
#    stop_loss_pct: 0.01  # 1%
#    strategy:
#      name: large_continuation
#      class: StrongContinuationStrategy
#      large_candle_percent: 0.3
#      wick_threshold: 0.02
#      ema_impulse_threshold: 0.0025
#      indicators:
#        - name: ema
#          length: 5
#    risk:
#      max_trades: 100
#      time_frame: 24h
#
#
#  - symbol: ZROUSD
#    quantity: 16
#    max_positions: 1
#    resolution: 3m
##    trailing_amount_pct: 0.01
#    ema_impulse_threshold: 0.0050
#    bootstrap_length: 300
#    leverage: 20
#    take_profit_pct: 0.005  # 0.25%
#    stop_loss_pct: 0.01  # 1%
#    strategy:
#      name: large_continuation
#      class: StrongContinuationStrategy
#      large_candle_percent: 0.3
#      wick_threshold: 0.02
#      ema_impulse_threshold: 0.0025
#      indicators:
#        - name: ema
#          length: 5
#    risk:
#      max_trades: 100
#      time_frame: 24h
#
#  - symbol: INJUSD
#    quantity: 8
#    max_positions: 1
#    resolution: 3m
##    trailing_amount_pct: 0.01
#    ema_impulse_threshold: 0.0050
#    bootstrap_length: 300
#    leverage: 20
#    take_profit_pct: 0.005  # 0.25%
#    stop_loss_pct: 0.01  # 1%
#    strategy:
#      name: large_continuation
#      class: StrongContinuationStrategy
#      large_candle_percent: 0.3
#      wick_threshold: 0.02
#      ema_impulse_threshold: 0.0025
#      indicators:
#        - name: ema
#          length: 5
#    risk:
#      max_trades: 100
#      time_frame: 24h
#
#  - symbol: SIGNUSD
#    quantity: 10
#    max_positions: 1
#    resolution: 3m
##    trailing_amount_pct: 0.01
#    ema_impulse_threshold: 0.0050
#    bootstrap_length: 300
#    leverage: 20
#    take_profit_pct: 0.005  # 0.25%
#    stop_loss_pct: 0.01  # 1%
#    strategy:
#      name: large_continuation
#      class: StrongContinuationStrategy
#      large_candle_percent: 0.3
#      wick_threshold: 0.02
#      ema_impulse_threshold: 0.0025
#      indicators:
#        - name: ema
#          length: 5
#    risk:
#      max_trades: 100
#      time_frame: 24h

  - symbol: INJUSD
    quantity: 4
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.005
#    ema_impulse_threshold: 0.0050
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.05  # 0.25%
#    stop_loss_pct: 0.01  # 1%
    strategy:
      name: super_trend_strategy
      class: SuperTrendImpulseStrategy
      wick_threshold: 0.02
      supertrend_diff_threshold: 0.4
      indicators:
        - name: supertrend
          length: 5
          multiplier: 1.2
    risk:
      max_trades: 100
      time_frame: 24h

  - symbol: KITEUSD
    quantity: 1
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.005
#    ema_impulse_threshold: 0.0050
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.02  # 0.25%
#    stop_loss_pct: 0.01  # 1%
    strategy:
      name: super_trend_strategy
      class: SuperTrendImpulseStrategy
      wick_threshold: 0.02
      supertrend_diff_threshold: 0.4
      indicators:
        - name: supertrend
          length: 5
          multiplier: 1.2
    risk:
      max_trades: 100
      time_frame: 24h

  - symbol: AIOUSD
    quantity: 3
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.005
#    ema_impulse_threshold: 0.0050
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.02  # 0.25%
#    stop_loss_pct: 0.01  # 1%
    strategy:
      name: super_trend_strategy
      class: SuperTrendImpulseStrategy
      wick_threshold: 0.02
      supertrend_diff_threshold: 0.4
      indicators:
        - name: supertrend
          length: 5
          multiplier: 1.2
    risk:
      max_trades: 100
      time_frame: 24h



execution:
  order_type: market

logging:
  level: DEBUG
