exchange:
  name: delta
  env: testnet
  rest_url: https://api.india.delta.exchange
  ws_url: wss://socket.india.delta.exchange
  api_key: ${DELTA_API_KEY}
  api_secret: ${DELTA_API_SECRET}

instruments:
  - symbol: INJUSD
    quantity: 1
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.005
#    ema_impulse_threshold: 0.0050
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.05  # 0.25%
#    stop_loss_pct: 0.01  # 1%
    strategy:
      name: super_trend_strategy
      class: SuperTrendImpulseStrategy
      wick_threshold: 0.02
      supertrend_diff_threshold: 0.4
      indicators:
        - name: supertrend
          length: 5
          multiplier: 1.2
    risk:
      max_trades: 100
      time_frame: 24h

  - symbol: KITEUSD
    quantity: 1
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.005
#    ema_impulse_threshold: 0.0050
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.02  # 0.25%
#    stop_loss_pct: 0.01  # 1%
    strategy:
      name: super_trend_strategy
      class: SuperTrendImpulseStrategy
      wick_threshold: 0.02
      supertrend_diff_threshold: 0.4
      indicators:
        - name: supertrend
          length: 5
          multiplier: 1.2
    risk:
      max_trades: 100
      time_frame: 24h

execution:
  order_type: market

logging:
  level: DEBUG
  # Directory inside the container where logs are stored.
  # You can volume‑mount this directory from the host, e.g.:
  #   -v /path/on/host/algo-logs:/app/logs
  dir: logs
  # Log file name inside the directory
  filename: app.log
  # Maximum size of each log file before rotation (in bytes)
  max_bytes: 52428800  # 5 MB
  # Number of rotated log files to keep
  backup_count: 5
