exchange:
  name: delta
  env: testnet
  rest_url: https://api.india.delta.exchange
  ws_url: wss://socket.india.delta.exchange
  api_key: ${DELTA_API_KEY}
  api_secret: ${DELTA_API_SECRET}

instruments:
  - symbol: INITUSD
    quantity: 20
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.01
    ema_impulse_threshold: 0.0075
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.02  # 2%
    stop_loss_pct: 0.01  # 1%
    strategy:
      name: supertrend_strategy
      class: Strategy2
      volume_multiplication: 1.5
      indicators:
        - name: ema
          length: 5
        - name: volume_sma
          length: 2
        - name: volume_sma
          length: 5
    risk:
      max_trades: 100
      time_frame: 24h

  - symbol: RIVERUSD
    quantity: 1
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.01
    ema_impulse_threshold: 0.0050
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.02  # 2%
    stop_loss_pct: 0.01  # 1%
    strategy:
      name: supertrend_strategy
      class: Strategy2
      volume_multiplication: 1.5
      indicators:
        - name: ema
          length: 5
        - name: volume_sma
          length: 2
        - name: volume_sma
          length: 5
    risk:
      max_trades: 100
      time_frame: 24h

  - symbol: VVVUSD
    quantity: 5
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.01
    ema_impulse_threshold: 0.0050
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.02  # 2%
    stop_loss_pct: 0.01  # 1%
    strategy:
      name: supertrend_strategy
      class: Strategy2
      volume_multiplication: 1.5
      indicators:
        - name: ema
          length: 5
        - name: volume_sma
          length: 2
        - name: volume_sma
          length: 5
    risk:
      max_trades: 100
      time_frame: 24h

  - symbol: JTOUSD
    quantity: 80
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.01
    ema_impulse_threshold: 0.0050
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.02  # 2%
    stop_loss_pct: 0.01  # 1%
    strategy:
      name: supertrend_strategy
      class: Strategy2
      volume_multiplication: 1.5
      indicators:
        - name: ema
          length: 5
        - name: volume_sma
          length: 2
        - name: volume_sma
          length: 5
    risk:
      max_trades: 100
      time_frame: 24h

  - symbol: ZORAUSD
    quantity: 10
    max_positions: 1
    resolution: 3m
    trailing_amount_pct: 0.01
    ema_impulse_threshold: 0.0050
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.02  # 2%
    stop_loss_pct: 0.01  # 1%
    strategy:
      name: supertrend_strategy
      class: Strategy2
      volume_multiplication: 1.5
      indicators:
        - name: ema
          length: 5
        - name: volume_sma
          length: 2
        - name: volume_sma
          length: 5
    risk:
      max_trades: 100
      time_frame: 24h

  - symbol: ETHUSD
    quantity: 1
    max_positions: 1
    resolution: 1m
    trailing_amount_pct: 0.01
    ema_impulse_threshold: 0.0040
    bootstrap_length: 300
    leverage: 20
    take_profit_pct: 0.05  # 2%
    stop_loss_pct: 0.01  # 1%
    strategy:
      name: supertrend_strategy
      class: Strategy2
      volume_multiplication: 2
      indicators:
        - name: ema
          length: 5
        - name: volume_sma
          length: 2
        - name: volume_sma
          length: 5
    risk:
      max_trades: 100
      time_frame: 24h


execution:
  order_type: market

logging:
  level: DEBUG
